apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard
spec:
  type: NodePort
  selector:
    app: k8s-dashboard
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # Fixed port for easier access
